name: dice_roller
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
 sdk: ^3.8.1

dependencies:
 flutter:
   sdk: flutter

dev_dependencies:
 flutter_test:
   sdk: flutter
 flutter_lints: ^5.0.0

flutter:
 assets:
   - lib/assets/images/dice-1.png
   - lib/assets/images/dice-2.png
   - lib/assets/images/dice-3.png
   - lib/assets/images/dice-4.png
   - lib/assets/images/dice-5.png
   - lib/assets/images/dice-6.png

 uses-material-design: true